force-app/main/default/objects/HRZ_CountryLayerSettings__mdt/HRZ_CountryLayerSettings__mdt.object-meta.xml
<CustomObject>
    <description>Settings for API Country Layer</description>
    <label>Country Layer Settings</label>
    <pluralLabel>Countries Layer Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/HRZ_CountryLayerSettings__mdt/fields/HRZ_AccessKey__c.field-meta.xml
<CustomField>
    <fullName>HRZ_AccessKey__c</fullName>
    <description>Access key for endpoint</description>
    <label>Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRZ_CountryLayerSettings__mdt/fields/HRZ_EndpointPath__c.field-meta.xml
<CustomField>
    <fullName>HRZ_EndpointPath__c</fullName>
    <description>Path for all records from Country Layer</description>
    <label>Endpoint Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HRZ_CountryLayerClient.cls
public without sharing class HRZ_CountryLayerClient implements Database.AllowsCallouts {
    
    public static List<Object> fetchAll() {
        HRZ_CountryLayerSettings__mdt countryLayerMeta = HRZ_CountryLayerSettings__mdt.getInstance('HRZ_CountryLayer');
        System.debug('countryLayerMeta: ' + countryLayerMeta);
        if (String.isBlank(countryLayerMeta.HRZ_AccessKey__c) || String.isBlank(countryLayerMeta.HRZ_EndpointPath__c)) {
            throw new HRZ_CountryLayerException('Missing HRZ CountryLayer settings.');
        }

        HttpRequest req = new HttpRequest();
        req.setMethod('GET');

        String endpoint = 'callout:HRZ_Country_Layer' + countryLayerMeta.HRZ_EndpointPath__c
            + '?access_key=' + EncodingUtil.urlEncode(countryLayerMeta.HRZ_AccessKey__c, 'UTF-8');

        req.setEndpoint(endpoint);
        System.debug('endpoint: ' + endpoint);

        HttpResponse res = new Http().send(req);
        Integer code = res.getStatusCode();
        if (code < 200 || code >= 300) {
            throw new HRZ_CountryLayerException('CountryLayer error: ' + code + ' - ' + res.getBody());
        }

        Object countriesInfo = JSON.deserializeUntyped(res.getBody());
                System.debug('countriesInfo: ' + countriesInfo);

        return (List<Object>) countriesInfo;
    }
    
        public class HRZ_CountryLayerException extends Exception {}
}