force-app/main/default/objects/HRZ_Country__c/HRZ_Country__c.object-meta.xml
<CustomObject>
    <description>Custom object to save country&apos;s information</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Alpha2Code__c</fullName>
    <description>Alpha2Code of the country</description>
    <externalId>true</externalId>
    <label>Alpha2Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Alpha3Code__c</fullName>
    <description>Alpha3Code of the country</description>
    <label>Alpha3Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Capital__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Capital__c</fullName>
    <description>Capital of the country</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Region__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Region__c</fullName>
    <description>Region of the country</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Regional_Blocs__c</fullName>
    <description>Acronyms for country</description>
    <label>Regional Blocs</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HRZ_CountrySyncService.cls
public with sharing class HRZ_CountrySyncService {
    
    @InvocableMethod
    public static void fetchCountryData() {
        List<Object> rawCountries = HRZ_CountryLayerClient.fetchAll();
        List<HRZ_Country__c> toUpsert = new List<HRZ_Country__c>();

        for (Object o : rawCountries) {

            Map<String, Object> countryMap = (Map<String, Object>) o;

            String name    = (String) countryMap.get('name');
            String alpha2  = (String) countryMap.get('alpha2Code');
            String alpha3  = (String) countryMap.get('alpha3Code');
            String capital = (String) countryMap.get('capital');
            String region  = (String) countryMap.get('region');
            Object regBlocsObj  = countryMap.get('altSpellings');
            
            if (String.isBlank(alpha2)) {
                continue;
            }
            List<String> regBlocsList = new List<String>();
            if(regBlocsObj != null){         
                List<Object> tempList = (List<Object>) regBlocsObj;

                for (Object reg : tempList) {
                    regBlocsList.add((String) reg);
                }
            }
            String regBlocs = String.join(regBlocsList,',');

            HRZ_Country__c c = new HRZ_Country__c();
            c.Name = name;
            c.HRZ_Alpha2Code__c = alpha2;
            c.HRZ_Alpha3Code__c = alpha3;
            c.HRZ_Capital__c = capital;
            c.HRZ_Region__c = region;
            c.HRZ_Regional_Blocs__c = regBlocs;

            toUpsert.add(c);
        }

        if (!toUpsert.isEmpty()) {
            upsert toUpsert HRZ_Alpha2Code__c;
        }
    }
}