force-app/main/default/objects/HRZ_Country__c/HRZ_Country__c.object-meta.xml
<CustomObject>
    <description>Custom object to save country&apos;s information</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Alpha2Code__c</fullName>
    <description>Alpha2Code of the country</description>
    <externalId>true</externalId>
    <label>Alpha2Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Latitude__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Latitude__c</fullName>
    <description>Latitude of the country</description>
    <label>Latitude</label>
    <precision>17</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Longitude__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Longitude__c</fullName>
    <description>Longitude of the country</description>
    <label>Longitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HRZ_Country__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship with Country custom object</description>
    <label>Country</label>
    <referenceTo>HRZ_Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRZ_LeadDAO.cls
/**
 * @description Data Access Object (DAO) class for Lead records.
 */
public with sharing class HRZ_LeadDAO {

    /**
     * @description Retrieves country geographical and identification data for a specific Lead record.
     * @param leadId The Id of the Lead record to retrieve country data for
     * @return Lead object containing HRZ_Country__r fields with geographical and identification data
     */
    public static Lead getCountryDataByLeadId(Id leadId) {
        return [
            SELECT HRZ_Country__r.HRZ_Latitude__c, HRZ_Country__r.HRZ_Longitude__c, 
                HRZ_Country__r.Name, HRZ_Country__r.HRZ_Alpha2Code__c 
                FROM Lead WHERE Id = :leadId LIMIT 1
            ];
    }
}