force-app/main/default/objects/HRZ_Country__c/HRZ_Country__c.object-meta.xml
<CustomObject>
    <description>Custom object to save country&apos;s information</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Alpha2Code__c</fullName>
    <description>Alpha2Code of the country</description>
    <externalId>true</externalId>
    <label>Alpha2Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Latitude__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Latitude__c</fullName>
    <description>Latitude of the country</description>
    <label>Latitude</label>
    <precision>17</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HRZ_Country__c/fields/HRZ_Longitude__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Longitude__c</fullName>
    <description>Longitude of the country</description>
    <label>Longitude</label>
    <precision>15</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HRZ_Country__c.field-meta.xml
<CustomField>
    <fullName>HRZ_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship with Country custom object</description>
    <label>Country</label>
    <referenceTo>HRZ_Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HRZ_LeadCountryMapService.cls
/**
 * @description Service class responsible for managing and mapping lead country-related operations.
 */
public with sharing class HRZ_LeadCountryMapService {
    /**
     * @description Retrieves geographical and descriptive data for a Lead's associated Country.
     * @param leadId The Id of the Lead record from which to retrieve country data
     * @return Map<String, Object> A map containing coutry data structured for use in a map component
     */
    public static Map<String, Object> getLeadCountryData(Id leadId) {
        Lead lead = HRZ_LeadDAO.getCountryDataByLeadId(leadId);
        
        if (lead.HRZ_Country__c == null) {
            return new Map<String, Object>{'hasCountry' => false};
        }
        
        return new Map<String, Object>{
            'hasCountry' => true,
            'center' => new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => lead.HRZ_Country__r.HRZ_Latitude__c,
                    'Longitude' => lead.HRZ_Country__r.HRZ_Longitude__c
                }
            },
            'markers' => new List<Object>{
                new Map<String, Object>{
                    'location' => new Map<String, Object>{
                        'Latitude' => lead.HRZ_Country__r.HRZ_Latitude__c,
                        'Longitude' => lead.HRZ_Country__r.HRZ_Longitude__c
                    },
                    'title' => lead.HRZ_Country__r.Name + ' (' + lead.HRZ_Country__r.HRZ_Alpha2Code__c + ')',
                    'description' => 'País del Lead: ' + lead.HRZ_Country__r.Name
                }
            },
            'countryName' => lead.HRZ_Country__r.Name
        };
    }
}